/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyTooltip {
        "message": string;
    }
    interface SpinnerLoad {
    }
    interface StockFinder {
    }
    interface StockPrice {
        "stockSym": string;
    }
    interface UcSideDrawer {
        "open": boolean;
        "openChange": () => Promise<void>;
        "title": string;
    }
}
declare global {
    interface HTMLMyTooltipElement extends Components.MyTooltip, HTMLStencilElement {
    }
    var HTMLMyTooltipElement: {
        prototype: HTMLMyTooltipElement;
        new (): HTMLMyTooltipElement;
    };
    interface HTMLSpinnerLoadElement extends Components.SpinnerLoad, HTMLStencilElement {
    }
    var HTMLSpinnerLoadElement: {
        prototype: HTMLSpinnerLoadElement;
        new (): HTMLSpinnerLoadElement;
    };
    interface HTMLStockFinderElement extends Components.StockFinder, HTMLStencilElement {
    }
    var HTMLStockFinderElement: {
        prototype: HTMLStockFinderElement;
        new (): HTMLStockFinderElement;
    };
    interface HTMLStockPriceElement extends Components.StockPrice, HTMLStencilElement {
    }
    var HTMLStockPriceElement: {
        prototype: HTMLStockPriceElement;
        new (): HTMLStockPriceElement;
    };
    interface HTMLUcSideDrawerElement extends Components.UcSideDrawer, HTMLStencilElement {
    }
    var HTMLUcSideDrawerElement: {
        prototype: HTMLUcSideDrawerElement;
        new (): HTMLUcSideDrawerElement;
    };
    interface HTMLElementTagNameMap {
        "my-tooltip": HTMLMyTooltipElement;
        "spinner-load": HTMLSpinnerLoadElement;
        "stock-finder": HTMLStockFinderElement;
        "stock-price": HTMLStockPriceElement;
        "uc-side-drawer": HTMLUcSideDrawerElement;
    }
}
declare namespace LocalJSX {
    interface MyTooltip {
        "message"?: string;
    }
    interface SpinnerLoad {
    }
    interface StockFinder {
        "onSymbolSelected"?: (event: CustomEvent<string>) => void;
    }
    interface StockPrice {
        "stockSym"?: string;
    }
    interface UcSideDrawer {
        "open"?: boolean;
        "title"?: string;
    }
    interface IntrinsicElements {
        "my-tooltip": MyTooltip;
        "spinner-load": SpinnerLoad;
        "stock-finder": StockFinder;
        "stock-price": StockPrice;
        "uc-side-drawer": UcSideDrawer;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-tooltip": LocalJSX.MyTooltip & JSXBase.HTMLAttributes<HTMLMyTooltipElement>;
            "spinner-load": LocalJSX.SpinnerLoad & JSXBase.HTMLAttributes<HTMLSpinnerLoadElement>;
            "stock-finder": LocalJSX.StockFinder & JSXBase.HTMLAttributes<HTMLStockFinderElement>;
            "stock-price": LocalJSX.StockPrice & JSXBase.HTMLAttributes<HTMLStockPriceElement>;
            "uc-side-drawer": LocalJSX.UcSideDrawer & JSXBase.HTMLAttributes<HTMLUcSideDrawerElement>;
        }
    }
}
